Shapes example
jezek/xgb pull request #4
Opened 2021-03-07 15:18 UTC by scrouthtv

TLDR: How to create a window and draw / fill things using `xproto`:
![image](https://user-images.githubusercontent.com/23227405/110244664-099ffd00-7f60-11eb-9f22-d49d3a7350bd.png)
(the white border outside the black border is generated by my WM, should not be there for you)

A bit of backstory: I originally got into `xgb` because I was working on a go implementation of the `xwd` (x window dump) file format and I needed to create small windows with randomly colored pixels, something like this:
![image](https://user-images.githubusercontent.com/23227405/110244691-33f1ba80-7f60-11eb-81a3-1c5c1fed1d87.png)
So I got into `xproto` and how to create images and such.

I cloned this example originally from [Alex Kesling's testing](https://github.com/akesling/Gonads/blob/master/sandbox/xgb_shapes.go) which is basically a Go copy of an example in the [`xcb` documentation](https://xcb.freedesktop.org/tutorial/basicwindowsanddrawing/).

I adapted some things to go nicer along the `create-window` example, added commentary and some more things (e. g. drawing text and filling a rectangle).

2021-03-07 15:20 UTC, scrouthtv commented
When I first was trying to use `xproto`, I couldn't figure out how I'd get the drawable that was needed for drawing.

I wanted one of the core aspects of this example to be demonstrating that the drawable is (for very basic use cases) the window itself.

2021-03-09 15:34 UTC, jezek requested changes
I took the libery to fix typos and reword a comment.
I had some difficulties running the example on Ubuntu (see comments near font).

Note: As you can see, I was able to push commit directly to your master branch. This is because you gave me permission to edit your PR. It's better practice to start a PR from a branch, so the maintainer (if granted privileges) can only edit the branch (and not master directly).

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +	foreground, _ := xproto.NewGcontextId(X)
Please check for error. I know, there is an error only if all IDs are depleted, and is impossible to happen in this example, but we don't want be a bad example for go learners. Always handle errors.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +	red, _ := xproto.NewGcontextId(X)
Handle error, please.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +	thick, _ := xproto.NewGcontextId(X)
Handle error, please.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +	blue, _ := xproto.NewGcontextId(X)
Handle error, please.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +	font, _ := xproto.NewFontId(X)
Handle error, please.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +		fmt.Println("Failed opening the font:", err)
I've got an:
```
Failed opening the font: BadName {NiceName: Name, Sequence: 8, BadValue: 67108870, MinorOpcode: 0, MajorOpcode: 45}
```
on Ubuntu MATE 20.10

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +	textCtx, _ := xproto.NewGcontextId(X)
Handle error, please.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +		if err != nil {
Why is this error heck here? Wouldn't it be better if it was right after WaitForEvent?

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +		evt, err := X.WaitForEvent()
Please check for evt == nil && err == nil and exit if catched. Or the example won't stop on Ubuntu if you close window.

2021-03-09 15:34 UTC, jezek commented on examples/shapes/main.go
> +		evt, err := X.WaitForEvent()
Please check for evt == nil && err == nil and exit if catched. Or the example won't stop on Ubuntu if you close window.

2021-03-09 16:16 UTC, scrouthtv commented
What are we going to do about the missing font issue? 

The example font that is often used is simply `fixed` (which is afaik installed by X).

However, I also want to demonstrate writing UTF8 characters (the ö), but `fixed` does only have a very limited character set.

I tried finding a font that would be preinstalled on many systems, looks like that didn't work out.

It is possible to see the available fonts using `xfontsel`.
`xproto` can also list available fonts to the developer using `ListFonts()`.

However, I don't know how to determine which of these support unicode characters.

2021-03-09 16:24 UTC, scrouthtv commented
Could you kindly try the font spec
`-*-*-*-*-*-*-14-*-*-*-*-*-iso10646-1`

2021-03-10 16:33 UTC, jezek commented
> However, I also want to demonstrate writing UTF8 characters (the ö), but `fixed` does only have a very limited character set.

I don't have a problem with `fixed`.
![shapes fixed](https://user-images.githubusercontent.com/5408235/110658954-6a2e7480-81c2-11eb-8da4-dff2f572d3f2.png)

But with unicode and fonts it's a little bit tricky (I think). If I wanted "more unicode" demonstration, I would pick a text like ```Hellö 世界!```, where the `fixed` font will fail like the `-*-*-*-*-*-*-14-*-*-*-*-*-iso10646-1` font (and maybe the `-gnu-unifont-*-*-*-*-16-*-*-*-*-*-*-*` too).
![shapes iso10646 jp](https://user-images.githubusercontent.com/5408235/110661282-b11d6980-81c4-11eb-9d7c-00cb143e1a27.png)

I'm a little bit in the dark, how to handle this, there is no easy solution (If there is, I would like to know). Few thing come into my mind, like bundle font with app and/or use enviroment variables, input lags or some config file to let the user choose desired font. But for simplicity of this example, I would go with `fixed` and  leave a comment about some possible drawbacks.

2021-03-10 16:44 UTC, jezek commented on examples/shapes/main.go
> +		} else if evt == nil && err == nil {
Here ```} else if evt == nil {``` is enough. No need to test for `err == nil`, cause we are in else clause of `err != nil`.

2021-03-10 19:42 UTC, scrouthtv commented
> I don't have a problem with `fixed`.

I just tried again, and now it's working for me too. I guess I just had something wrong during my first tries.

> `-*-*-*-*-*-*-14-*-*-*-*-*-iso10646-1`

This simply selectes any font that is iso10646-1 encoded, which is basically the character encoding of Unicode. So any of these fonts should have at least a basic set of extended latin characters.

> But for simplicity of this example, I would go with fixed and leave a comment about some possible drawbacks.

Sounds good!

2021-03-12 15:07 UTC, merged